config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :people
  resources :venues
  resources :games, only: [:index]
  resources :participants
  resources :matches
  resources :teams
  resources :leagues
  resources :clubs
  resources :seasons

  get 'club', to:  redirect('/clubs')

  root to: 'leagues#index'

end

app/models/league.rb
class League < ActiveRecord::Base
	belongs_to :season
	has_many :teams
	has_many :matches
	has_many :games, through: :matches

	def make_pairing(weeks=nil)
		weeks ||= 5.times.map { |i| Date.today.cweek + 2*(i+1) }
		pairing = round_robin_pairing(teams.to_a)
		pairing.each.with_index do |pairs,round|
			pairs.each do |home, away|
				venue = home.club.venues.first || Venue.first
				play_date = Date.commercial(Date.today.year, weeks[round], venue.playing_day)
				matches.create(black_team: home, white_team: away, venue: venue, playing_date: play_date, playing_time: venue.playing_time)
			end
		end
	end

	def drop_pairing
		matches.destroy_all
	end

	def round_robin_pairing(participants)
		return nil if participants.length < 3
		participants = participants.dup
		participants << nil if participants.length.odd?

		boards = participants.length / 2
		fixed  = participants.shift
		rounds = Array.new(participants.length) do |index|
			participants.unshift(fixed)
			round = boards.times.map do |board|
				index.odd? ? [participants[board], participants[-board-1]] : [participants[-board-1], participants[board]]
			end
			participants.shift
			participants.rotate!(-1)
			round
		end
	end

	def direct_comparison
		teams.product(teams).each do |team1, team2|
			table[team1.id] ||= {}
			table[team1.id][team2.id] = if team1.score == team2.score && team1.points == team2.points
				0
			else
				nil
			end
		end
		matches.each do |match|
			if table[match.black_team_id][match.white_team_id]
				table[match.black_team_id][match.white_team_id] = [match.black_score, match.black_points]
				table[match.white_team_id][match.black_team_id] = [match.white_score, match.white_points]
			end
		end
	end


	def standings
		return @standings if @standings
		teams = self.teams.to_a.sort_by(&:placement_criteria).reverse
		table = Hash.new
		teams.product(teams).each do |team1, team2|
			table[team1.id] ||= {}
			table[team1.id][team2.id] = {}
		end
		matches.each do |match|
			table[match.black_team_id][match.white_team_id] = [
				match,
				match.played? ? match.black_points : nil,
				match.played? ? (match.black_score == 1 ? 'won' : 'lost') : 'unplayed',
				match.venue
			]
			table[match.white_team_id][match.black_team_id] = [
				match,
				match.played? ? match.white_points : nil,
				match.played? ? (match.white_score == 1 ? 'won' : 'lost') : 'unplayed',
				match.venue
			]
		end
		@standings = table
	end

	def team_ordered_players

	end

	def full_results
		teams = self.teams.to_a.sort_by(&:placement_criteria).reverse
		pairing = round_robin_pairing(teams)
		table = Hash.new
		teams.each do |team|
			table[team.id] = Hash.new
			table[team.id][:matches] = Hash.new
		end
		pairing.each do |round|
			round.each do |team1, team2|
				match = Match.find_by_teams(team1, team2)
				table[team1.id][:matches][match.id] = match
				table[team2.id][:matches][match.id] = match
			end
		end
		teams.each do |team|
			players = (team.black_matches.map(&:games).map(&:black_player).map(&:id) + team.white_matches.map(&:games).map(&:white_player).map(&:id)).flatten.uniq
		end
	end

	def results
		res = Hash.new
		teams.sort_by(&:placement_criteria).reverse.each do |team|
			team.team_members.includes(:participant).order(:board_number).map(&:participant).each do |participant|
				res[participant.id] ||= Array.new
			end
		end
		games.each do |game|
			res[game.black_id] ||= Array.new
			res[game.white_id] ||= Array.new
			free = 0
			free += 1 while res[game.black_id][free] || res[game.white_id][free]
			res[game.black_id][free] = [game, game.white_id, game.black_result]
			res[game.white_id][free] = [game, game.black_id, game.white_result]
		end
		res.each_with_index do |(pid,games), i|
			games.each_with_index do |game, j|
				if game.nil?
					res[pid][j] = [nil, nil, '=', 0]
				elsif game[0].forfeit?
					res[game[1]][j] << 0
				else
					res[game[1]][j] << i+1
				end
			end
		end
		width = res.map { |k,v| v.length }.max
		player_list = res.map.with_index do |(pid,games), i|
			p = Participant.find(pid)
			[
				i+1, 
				"%-30s" % [p.lastname, p.firstname].map(&:strip).join(' '),
				p.rank,
				"NL",
				p.club.abbrev,
				p.team_member.present? ? p.team_member.board_number : 0,
				"%.2f" % (100 * p.rating_change),
				games.select { |game| "#{game[2]}" == '+' }.length,
				games.map { |game| "#{game[3]}#{game[2]}" },
				(games.length...width).map { "0=" }
			].flatten.map(&:to_s).join("\t")
		end
		teams_list = teams.sort_by(&:placement_criteria).reverse + [OpenStruct.new(name: "Reserves")]
		results_list = player_list.each_slice(3).zip(teams_list).map { |p,t| [t ? "; #{t.name}" : nil, p] }.flatten.compact
	end


end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
	before_action :set_league, only: [:show, :edit, :update, :destroy]

	def index
		@leagues = @season.leagues.order(:order).includes(:teams, matches: :games)
		@matches = @season.matches.includes(:black_team, :white_team, :games)
	end

	def show
		@participants = Participant.joins(:team_member).where('team_members.team_id' => @league.teams.pluck(:id))
		@participants = @participants.to_a.sort_by(&:rating_change).reverse
		@teams = @league.teams
		@matches = @league.matches.order(:playing_date, :playing_time)
		respond_to do |format|
			format.text { render text: @league.results.join("\n")}
			format.html
		end
	end

	def new
		@league = @season.leagues.build
	end

	def edit
	end

	def create
		@league = League.new(league_params)

		respond_to do |format|
			if @league.save
				format.html { redirect_to @league, notice: 'League was successfully created.' }
				format.json { render action: 'show', status: :created, location: @league }
			else
				format.html { render action: 'new' }
				format.json { render json: @league.errors, status: :unprocessable_entity }
			end
		end
	end

	def update
		respond_to do |format|
			if @league.update(league_params)
				format.html { redirect_to @league, notice: 'League was successfully updated.' }
				format.json { head :no_content }
			else
				format.html { render action: 'edit' }
				format.json { render json: @league.errors, status: :unprocessable_entity }
			end
		end
	end

	def destroy
		@league.destroy
		respond_to do |format|
			format.html { redirect_to leagues_url }
			format.json { head :no_content }
		end
	end

	private
	def set_league
		@league = League.find(params[:id])
	end

	def league_params
		params.require(:league).permit(:name, :order, :season_id)
	end
end

app/views/leagues/_form.html.haml
.form_inputs
	= f.association :season
	= f.input :name
	= f.input :order

app/views/leagues/_standings.html.haml
- teams = league.teams.to_a.sort_by(&:placement_criteria).reverse
%table.league-standings
	%tr
		%th.team-name
		- teams.each do |team|
			%th.team-abbrev= team.abbrev
		%th.pts WP
		%th.pts BP
	- teams.each do |team1|
		%tr
			%th.team-name
				= link_to team1 do
					%span.show-for-medium-up= team1.name
					%span.hide-for-medium-up= team1.abbrev
				- teams.each do |team2|
					- if team1.id == team2.id
						%td &times;
					- else
						- if league.standings[team1.id][team2.id].empty?
							%td
								-if current_user
									= link_to '>>', new_match_path(league_id: league.id, black_team_id: team1.id, white_team_id: team2.id)
						- else
							- match, result, status, venue = league.standings[team1.id][team2.id]
							%td{class: status}
								= link_to match, title: match.venue_city do
									- if result
										= result
									- else 
										%span{style:'font-size:85%'}= match.playing_date.strftime("%e/%-m")
				%th= team1.score
			%th= team1.points
	- if @fill_rows_upto
		- (@fill_rows_upto - teams.length).times do
			%tr.show-for-large-up
				%th.team-name
				- teams.length.times do
					%td
						%small &nbsp;
				%th &nbsp;
				%th &nbsp;

app/views/leagues/edit.html.haml
%h2 Poule Bewerken
%section
	= simple_form_for @league do |f|
		= render 'form', f: f
		.form_actions
			= f.submit 'Opslaan', class: 'button'

app/views/leagues/index.html.haml
- if @season.information.present?
	%section
		= markdown @season.information
	%hr
%h2 Stand #{@season.name}
- @leagues.each_slice(2) do |league1,league2|
	.row
		.small-12.large-6.columns
			%h3= link_to league1.name, league1
			= render partial: 'standings', locals: { league: league1, :@fill_rows_upto => 6 }
		- if league2
			.small-12.large-6.columns
				%h3= link_to league2.name, league2
				= render partial: 'standings', locals: { league: league2, :@fill_rows_upto => 6 }

app/views/leagues/new.html.haml
%h2 Nieuwe poule
%section
	= simple_form_for @league do |f|
		= render 'form', f: f

		.form_actions
			= f.submit 'Opslaan', class: 'button'

app/views/leagues/show.html.haml
%h2= @league.name
%section
	%h3 Stand
	= render partial: 'standings', locals: { league: @league }
%section
	%h3 Wedstrijden
	= render @matches, :@show => [:venue, :date]
%hr
%section
	%h3 Teams
	= render @teams

- if current_user
	%hr
	%section
		%h3 Spelers
		= render @participants
	%hr
	%section
		= link_to 'Poule Bewerken', edit_league_path(@league), class: 'button'
		= link_to 'Team Toevoegen', new_team_path(league_id: @league.id), class: 'button'