config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :people
  resources :venues
  resources :games, only: [:index]
  resources :participants
  resources :matches
  resources :teams
  resources :leagues
  resources :clubs
  resources :seasons

  get 'club', to:  redirect('/clubs')

  root to: 'leagues#index'

end

app/models/person.rb
require 'open-uri'

class Person < ActiveRecord::Base
	has_many :participants

	def name
		"#{firstname.gsub('_',' ')} #{lastname.gsub('_',' ')}" 
	end		

	def rank=(value)
		value = value.to_i if value =~ /\A(\d+)\Z/
		self[:rank] = case value
		when 1..69 then value
		when /\A(\d)\s*(dan)?\s*p/i then $1.to_i + 60
		when /\Apro/i then 60
		when /\A(\d)\s*d/i then $1.to_i + 50
		when /\A([1-4]?\d)\s*k/i then 51 - $1.to_i
		else 0
		end
	end

	def rank
		case self[:rank]
		when 61..69 then "#{self[:rank] - 60}p"
		when 60 then 'pro'
		when 51..59 then "#{self[:rank] - 50}d"
		when 1..50 then "#{51 - self[:rank]}k"
		else ""
		end
	end

	def absorb(other_person)
		# TODO: for merging duplicates
	end

	# Example entry of the EGD json for a player
	# {
	# 	"Pin_Player":"10537560",
	# 	"AGAID":"0",
	# 	"Last_Name":"Aaij",
	# 	"Name":"Rene",
	# 	"Country_Code":"NL",
	# 	"Club":"Gron",
	# 	"Grade":"4d",
	# 	"Grade_n":"33",
	# 	"EGF_Placement":"175",
	# 	"Gor":"2402",
	# 	"DGor":"0",
	# 	"Proposed_Grade":"",
	# 	"Tot_Tournaments":"84",
	# 	"Last_Appearance":"T170114F",
	# 	"Elab_Date":"2009-04-03",
	# 	"Hidden_History":"0",
	# 	"Real_Last_Name":"Aaij",
	# 	"Real_Name":"Rene"
	# },

	def self.update_all_from_egd
		open('http://www.europeangodatabase.eu/EGD/GetPlayerDataByData.php?lastname=%&country=nl') do |egd_json|
			egd_data = JSON.load(egd_json)
			egd_data['players'].map do |player|
				club = Club.find_or_create_by(abbrev: player['Club'])

				person = Person.find_or_build_by(egd_pin: player['Pin_Player'])
				person.update_attributes(
					rating: player['Gor'].to_i,
					rank: player['Grade'],
					lastname: player['Real_Last_Name'],
					firstname: player['Real_Name'],
					club_id: club.id
				)
				person.save
			end
		end
	end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
	before_action :set_person, only: [:show, :edit, :update, :destroy]

	def index
		@people = Person.all
	end

	def show
	end

	def new
		@person = Person.new
	end

	def edit
	end

	def create
		@person = Person.new(person_params)

		respond_to do |format|
			if @person.save
				format.html { redirect_to @person, notice: 'Person was successfully created.' }
				format.json { render action: 'show', status: :created, location: @person }
			else
				format.html { render action: 'new' }
				format.json { render json: @person.errors, status: :unprocessable_entity }
			end
		end
	end

	def update
		respond_to do |format|
			if @person.update(person_params)
				format.html { redirect_to @person, notice: 'Person was successfully updated.' }
				format.json { head :no_content }
			else
				format.html { render action: 'edit' }
				format.json { render json: @person.errors, status: :unprocessable_entity }
			end
		end
	end

	def destroy
		@person.destroy
		respond_to do |format|
			format.html { redirect_to people_url }
			format.json { head :no_content }
		end
	end

	private
		def set_person
			@person = Person.find(params[:id])
		end

		def person_params
			params.require(:person).permit(:firstname, :lastname, :egd_pin, :email, :email2, :phone, :phone2)
		end
end

app/views/people/_form.html.haml
= simple_form_for(@person) do |f|
	= f.error_notification

	.form-inputs
		= f.input :firstname
		= f.input :lastname
		= f.input :egd_pin
		= f.input :email
		= f.input :email2
		= f.input :phone
		= f.input :phone2

	.form-actions
		= f.button :submit

app/views/people/_person.html.haml
= person.firstname
= person.lastname
- if current_user
	%br
	Email:
	= [person.email, person.email2].reject(&:blank?).join(' of ')
	%br
	Telefoon:
	= [person.phone, person.phone2].reject(&:blank?).join(' of ')

app/views/people/edit.html.haml
%h2 Persoon bewerken
%section
	= render 'form'

app/views/people/index.html.haml
%h2 Personen
%section
	=render @people
- if current_user
	%hr
	%section
		= link_to 'New Person', new_person_path

app/views/people/new.html.haml
%h1 Nieuwe Persoon
%section
	= render 'form'

app/views/people/show.html.haml
%h2= @person.name

%section
	%br
	%strong Email:
	= @person.email
	%br
	%strong Email 2:
	= @person.email2
	%br
	%strong Telefoon:
	= @person.phone
	%br
	%strong Telefoon 2:
	= @person.phone2
- if current_user
	%hr
	%section
		= link_to 'Persoon Bewerken', edit_person_path(@person), class: 'button'