config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :people
  resources :venues
  resources :games, only: [:index]
  resources :participants
  resources :matches
  resources :teams
  resources :leagues
  resources :clubs
  resources :seasons

  get 'club', to:  redirect('/clubs')

  root to: 'leagues#index'

end

app/models/participant.rb
class Participant < ActiveRecord::Base
	belongs_to :club
	belongs_to :season
	belongs_to :person
	validates_presence_of :season
#	before_create :copy_person_attributes
	has_one :team_member
	has_many :black_games, class_name: 'Game', foreign_key: :black_id
	has_many :white_games, class_name: 'Game', foreign_key: :white_id

	def copy_person_attributes
		self.assign_attributes(person.attributes.with_indifferent_access.slice(:club_id, :firstname, :lastname, :rating, :egd_pin, :rank))
	end

	def name
		"#{firstname.gsub('_',' ')} #{lastname.gsub('_',' ')} (#{rating})" 
	end

	def fullname
		"#{firstname.gsub('_',' ')} #{lastname.gsub('_',' ')}"
	end

	def games
		Game.where('black_id = ? OR white_id = ?', self.id, self.id)
	end

	def played_games
		games.played
	end

	def rating_change
		black_games.played.map(&:black_rating_change).sum + white_games.played.map(&:white_rating_change).sum
	end

	def rating_performance
		"#{(rating_change * 100).round(2)}%"
	end

	def rank=(value)
		value = value.to_i if value =~ /\A(\d+)\Z/
		self[:rank] = case value
		when 1..69 then value
		when /\A(\d)\s*(dan)?\s*p/i then $1.to_i + 60
		when /\Apro/i then 60
		when /\A(\d)\s*d/i then $1.to_i + 50
		when /\A([1-4]?\d)\s*k/i then 51 - $1.to_i
		else 0
		end
	end

	def rank
		case self[:rank]
		when 61..69 then "#{self[:rank] - 60}p"
		when 60 then 'pro'
		when 51..59 then "#{self[:rank] - 50}d"
		when 1..50 then "#{51 - self[:rank]}k"
		else ""
		end
	end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
	before_action :set_participant, only: [:show, :edit, :update, :destroy]

	def index
		@participants = @season.participants.includes(:club).order('rating DESC')
	end

	def show
		@games = @participant.games
	end

	def new
		@participant = Participant.new
	end

	def edit
	end

	def create
		@participant = Participant.new(participant_params)
		if @participant.season_id.blank?
			@participant.season = Season.last
		end

		respond_to do |format|
			if @participant.save
				format.html { redirect_to @participant, notice: 'Participant was successfully created.' }
				format.json { render action: 'show', status: :created, location: @participant }
			else
				format.html { render action: 'new' }
				format.json { render json: @participant.errors, status: :unprocessable_entity }
			end
		end
	end

	def update
		respond_to do |format|
			if @participant.update(participant_params)
				format.html { redirect_to @participant, notice: 'Participant was successfully updated.' }
				format.json { head :no_content }
			else
				format.html { render action: 'edit' }
				format.json { render json: @participant.errors, status: :unprocessable_entity }
			end
		end
	end

	def destroy
		@participant.destroy
		respond_to do |format|
			format.html { redirect_to participants_url }
			format.json { head :no_content }
		end
	end

	private
		def set_participant
			@participant = Participant.find(params[:id])
		end

		def participant_params
			params.require(:participant).permit(:firstname, :lastname, :rating, :egd_pin, :club_id, :season_id, :rank)
		end
end

app/views/participants/_form.html.haml
= simple_form_for(@participant) do |f|
	= f.error_notification

	.form-inputs
		= f.input :firstname
		= f.input :lastname
		= f.input :rating
		= f.input :egd_pin
		= f.input :rank, as: :string, input_html: { value: f.object.rank }
		= f.association :club

	.form-actions
		= f.submit 'Opslaan', class: 'button'

app/views/participants/_participant.html.haml
.row
	.small-8.medium-5.columns
		-if participant.games.count > 0
			%b= link_to participant.fullname, participant
		-else
			= link_to participant.fullname, participant
	- if current_user
		.small-2.medium-1.columns= participant.rating
		.small-2.medium-1.columns= participant.rating_performance
	- else
		.small-4.medium-2.columns= participant.rating
	.medium-5.columns.hide-for-small
		- if participant.team_member
			%b= link_to participant.team_member.team.name, participant.team_member.team
		- elsif @show_club
			= link_to participant.club.name, participant.club

app/views/participants/edit.html.haml
%h2 Deelnemer bewerken

= render 'form'

app/views/participants/index.html.haml
%h2 Alle deelnemers
%section
	= render @participants
- if current_user
	%hr
	%section
		= link_to 'Deelnemer Toevoegen', new_participant_path, class: 'button'

app/views/participants/new.html.haml
%h2 Nieuwe deelnemer
%section
	= render 'form'

app/views/participants/show.html.haml
%h2= @participant.name
%section
	Seizoen: #{@participant.season.name}
	%br
	Club:
	= link_to @participant.club.name, @participant.club
	%br
	- if @participant.team_member
		Team:
		= link_to @participant.team_member.team.name, @participant.team_member.team
	%br
	Individuele prestatie: #{@participant.rating_performance}

%hr
%section
	%h3 Partijen
	= render @games

- if current_user
	%hr
	%section
		= link_to 'Deelnemer bewerken', edit_participant_path(@participant), class: 'button'