config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :people
  resources :venues
  resources :games, only: [:index]
  resources :participants
  resources :matches
  resources :teams
  resources :leagues
  resources :clubs
  resources :seasons

  get 'club', to:  redirect('/clubs')

  root to: 'leagues#index'

end

app/views/layouts/application.html.haml
!!! 5
%html{ :lang => "en"}
	%head
		%meta{ :charset => "utf-8" }
		%meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

		%title= content_for?(:title) ? yield(:title) : "NGC #{@season.name}"

		= stylesheet_link_tag "application"
		= javascript_include_tag "vendor/modernizr"
		= csrf_meta_tag

	%body
		.contain-to-grid.sticky
			%nav.top-bar{data: { topbar: '' }}
				%ul.title-area
					%li.name
						%h1= link_to "NGC", root_path
					%li.toggle-topbar.menu-icon
						= link_to 'Menu', '#'
				%section.top-bar-section
					%ul.right
						- if current_user
							%li.has-dropdown
								= link_to current_user.email, '#'
								%ul.dropdown
									%li= link_to 'Uitloggen', destroy_user_session_path, method: :delete
						- else
							%li
								= link_to 'Inloggen', new_user_session_path					
					%ul.left
						%li= link_to 'Stand', root_path
						%li= link_to 'Rooster', matches_path
						%li= link_to 'Teams', teams_path
						%li= link_to 'Clubs', clubs_path
						%li= link_to 'Lokaties', venues_path
						%li.has-dropdown
							= link_to 'Archief', '#'
							%ul.dropdown
								- Season.all.order(created_at: :desc).each do |season|
									%li= link_to season.name, "//#{season.slug}.gocompetitie.nl/"
		.row
			.small-12.columns
				- if flash[:alert]
					.alert-box.warning{data: {alert: ''}}
						= alert
				- if flash[:notice]
					.alert-box{data: {alert: ''}}
						= notice
		.row
			.small-12.columns
				= yield

		= javascript_include_tag "application"